version: '3'

services:

  nginx:
    container_name: nginx
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - "8090:443"
    depends_on:
      - phpmyadmin1
      - phpmyadmin2


  mysql_master:
    image: mysql:latest
    container_name: mysql_master
    command: --server-id=1 --log-bin=mysql-bin --binlog-do-db=replica
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: replica
    ports:
      - "3308:3306"

  mysql_maestro:
    image: mysql:latest
    container_name: mysql_maestro
    command: --server-id=2 --log-bin=mysql-bin --binlog-do-db=replica
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: replica
    ports:
      - "3309:33060"

  phpmyadmin1:
    image: phpmyadmin/phpmyadmin:latest
    container_name: phpmyadmin1
    environment:
      PMA_HOST: "mysql_master"
      PMA_ARBITRARY: 1
      PMA_USER: root
      PMA_PASSWORD: root
    depends_on:
      - mysql_master #Especifica que este servicio depende de los servicios mysql_master y mysql_slave.
    ports:
      - "8080:80"

  phpmyadmin2:
    image: phpmyadmin/phpmyadmin:latest
    container_name: phpmyadmin2
    environment:
      PMA_HOST: "mysql_maestro"
      PMA_ARBITRARY: 1
      PMA_USER: root
      PMA_PASSWORD: root
    depends_on:
      - mysql_maestro
    ports:
      - "8081:80"